version: '1.8.{build}'

configuration: Release
platform: Any CPU
image: Visual Studio 2017
shallow_clone: true

install:
- cmd: choco install InnoSetup

before_build:
- nuget restore -Verbosity quiet Source\MOSA.sln

build:
  verbosity: minimal
  parallel: true
  project: Source\MOSA.sln
  publish_nuget: true

after_build:
- cmd: Source\Inno-Setup-Script\create-installer.bat

build_script:

after_test:

nuget:
  project_feed: true

test: off

assembly_info:
  patch: true
  file: AssemblyInfo.*
  assembly_version: "1.8.{build}"
  assembly_file_version: "{version}"
  assembly_informational_version: "{version}"

artifacts:
- path: 'bin\MOSA Installer\MOSA-Installer.exe'
